# Generated by Django 3.1.4 on 2020-12-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articleimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_id',
        ),
    ]
